blank_issues_enabled: false
contact_links:
  - name: Questions, Discussions, Ideas
    url: https://github.com/BoTech-Development/BoTech.DesignerForAvalonia/discussions/new
    about: Please ask and answer questions here
