name: Feature request
description: Suggest an idea for this project
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to ani issue? Please describe and paste a link of the issue.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Which feature should be implemented.
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Do you have an idea how to implement your feature?
      description: A clear and precise description of how we can implement the feature. Please use the repository as reference
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
